### ISSUE TITLE
SPA Crashes

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/wh2o-vue#13]
I can rarely use the SPA for more than 10 minutes before it freezes Safari and I have to close and restart the whole browser. 

May be caused by the News Tab, which does not load news or alerts

**Comment by drewalth** [comment]
@AWKevin I had accidentally triggered an infinite loop in the news tab. It has been addressed. 

To test, please wait for the Update Available notification and install.

[https://wh2o-vue.herokuapp.com/#/river-detail/356/news](https://wh2o-vue.herokuapp.com/#/river-detail/356/news)
