### ISSUE TITLE
Main NWI = No Color Code or Flows

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/wh2o-vue#134]
**Describe the bug**
When I go to the main NWI page and zoom in, the list on the right column does not display the color code, nor the numeric flow right now. 

**To Reproduce**
1. Go to https://test.americanwhitewater.org/content/River/view/?#/river-index
2. Zoom in. 
3. look at the list

**Expected behavior**
Each river should be color coded for flow category, and have a numeric flow next to it. 

**Screenshots**
<img width="1417" alt="Screen Shot 2020-07-30 at 12 14 45 PM" src="https://user-images.githubusercontent.com/7936679/88947618-c6114200-d25e-11ea-96df-bf45b0580c5f.png">

**Desktop (please complete the following information):**
 - Safari

**Comment by ngottlieb** [comment]
@mattanger is the gauge server running on test? maybe there's some other architectural thing going on?

**Comment by ngottlieb** [comment]
oh, nvm, I know what's going on -- I made a change on `wh2o` that @ryangroth5 merged the other day but probably hasn't been updated on test?

**Comment by ngottlieb** [comment]
@AWKevin the gauge server wasn't running on Test. I ran the USGS import which should bring in about 40% of gauges and then I turned on the gauge server (I think, first time doing that), so it should be working going forward.
