### ISSUE TITLE
Rapids are in reverse order

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/wh2o-vue#24]
They should go from put it at top to take out at bottom, but are reversed: 

https://wh2o-vue.herokuapp.com/#/river-detail/1039/main

**Comment by drewalth** [comment]
@ryangroth5 , I've tried sorting these by distance on the front end but end up triggering infinite loops. Might be easiest for the API to handle the sort?

![image](https://user-images.githubusercontent.com/16584198/80848734-7aa0b680-8bd1-11ea-8474-1550009b1a85.png)

![image](https://user-images.githubusercontent.com/16584198/80848738-7ffe0100-8bd1-11ea-85a6-a7ec24f3cd17.png)

**Comment by ryangroth5** [comment]
Weird, are you using a calculated field?

Ryan

**Comment by drewalth** [comment]
I'd prefer the sorting to happen on the API side and not in the browser.
