### ISSUE TITLE
Incorporate geospatial editor for Reach Updating

### ISSUE THREAD

**Issue by ngottlieb** [AmericanWhitewater/wh2o-vue#27]
Seth wrote code for this in the PHP app, hopefully it can be repurposed. It's been sitting here for 6 months or so. https://github.com/AmericanWhitewater/wh2o/pull/1637/files

At a minimum, we need to replicate the original functionality for editing location data on put-ins, take-outs, and rapids.

Current plan is for @drewalth to put skeleton components in place for this and @ngottlieb will fill them in, replicating Seth's original code as best as possible.

**Comment by ryangroth5** [comment]
Sweet

**Comment by ngottlieb** [comment]
https://github.com/AmericanWhitewater/wh2o-vue/pull/67 *largely* solves this but isn't ready to be merged.

There is one potential question: this PR uses the existing reach geom in our database for snapping. If you're creating a new reach, you won't have that. Can we create reaches with the put-in and takeout and a separate editor, then add rapids after saving them? (NOTE: *maybe* we can use the NHD snapping for put-in/takeout editor to actually create and save geom with Javascript, thus bypassing the entire need for a server-side processing of NHD geoms)

Still left to do:

- [ ] calculate "distance" on the fly

**Comment by ngottlieb** [comment]
additional thought for the big question above: if we are able to generate a geom in Javascript from the put-in and takeout (and the NHD tiles served from mapbox)...then we can store that geom as the reach state, which will allow it to be used in the rapid editors even if the reach has not been saved.  🎉 🎉
