### ISSUE TITLE
Comments are unordered

### ISSUE THREAD

**Issue by ingalls** [AmericanWhitewater/wh2o-vue#31]
### Context

Comments are not ordered by date

![Screenshot from 2020-04-29 19-13-11](https://user-images.githubusercontent.com/1297009/80665159-8a8f8d80-8a4d-11ea-9932-bfb34221683c.png)

### Actions

- [ ] Order comments by date DESC

**Comment by drewalth** [comment]
@ryangroth5 , might be an API issue? Or am I not setting up the query correctly?

```
const fetchCommentsData = data => {
  return httpClient
    .post('/graphql', {
      query: `
        query {
            posts(reach_id: "${data}", post_types: COMMENT, page: 1, orderBy: {field: REVISION, order: DESC}, first: 10) {
              data {
                id
                title
                detail
                post_date
                revision
                post_type
                user {
                  uname
                  uid
                  image {
                    uri {
                      thumb
                      medium
                      big
                    }
                  }
                }
              }
            }
          }

    `
    })
    .then(res => res.data)
}
```

![image](https://user-images.githubusercontent.com/16584198/80848540-d61e7480-8bd0-11ea-8c51-d4b404271d01.png)

**Comment by ryangroth5** [comment]
revision will be in order of edit.
so like if a comment was edited it will bubble to the top
but it won't guarantee order by date, which might be messed up when
revisions were assigned at import
can you order by another field? not sure.
