### ISSUE TITLE
Map UI Actions next to search

### ISSUE THREAD

**Issue by ingalls** [AmericanWhitewater/wh2o-vue#33]
### Context

I was initially very confused by the layer switcher & fullscreeen button as they were spatially disassociated from the map. How would folks feel about putting the fullscreen component & layer changer on the map interface itself in the upper right hand corner.

### Actions

- [ ] Potentially move fullscreen/layer switcher onto map

### Image

![Screenshot from 2020-04-29 19-24-15](https://user-images.githubusercontent.com/1297009/80665708-1524bc80-8a4f-11ea-8cf3-935615817f5d.png)

@drewalth

**Comment by ngottlieb** [comment]
Hey @ingalls -- so my original UX for this was with an overlay bar on top of the map. You can actually see it (although it's *slightly* broken) here: https://beta.americanwhitewater.org/content/River/view/. Do you think that's better?

I'm not sure what's best and @drewalth moved it to the side with some rationale, but given @ingalls's thoughts on this maybe we should reinstate the old control bar, or some combination of the two?

**Comment by ngottlieb** [comment]
Resolved, we moved the layer switcher and full screen toggle onto the map as per your suggestion @ingalls. Thanks!
