### ISSUE TITLE
Update packages as needed on Vue app

### ISSUE THREAD

**Issue by ngottlieb** [AmericanWhitewater/wh2o-vue#495]
[Github build process on Vue app broken#2658](https://github.com/AmericanWhitewater/wh2o/issues/2658) made it clear that we are way behind on keeping our libraries up to date. At a minimum, we should check on the PR's submitted by dependabot, but we should also look at updating other packages where possible and consider creating another task to update Node (in the codebase *and* on beta/prod).

**Comment by ngottlieb** [comment]
OK, I've tackled a lot of the stuff indicated by `npm audit` and some others here and will submit a PR. I suggest we make additional specific tasks to cover further upgrading, in rough order of increasing complexity:

- determine if we are using `vue-cli-plugin-apollo`, an unmaintained library, and remove if not (many of our vulnerabilities come from this)
- replace moment.js with a more modern date library (resolves one vulnerability)
- upgrade `vue-cli-service` to 5.x (4->5 includes breaking changes; resolves many of our remaining audit vulnerabilities)
- upgrade to vue 3 (big task)

**Comment by ngottlieb** [comment]
PR awaiting review. I've done some testing of these changes and have found no problems but probably best to have this sitting on beta (once reviewed) for a bit so staff can identify anything I might have missed.

**Comment by ngottlieb** [comment]
ok, this is on beta now, just going to leave it there as we test other tasks and hopefully that will identify any issues (though I don't think there are any)

**Comment by ngottlieb** [comment]
I created four new tasks to track the suggestions I made above:

- #528 
- #529 
- #530 
- #532

**Comment by AWKevin** [comment]
@ngottlieb this is not testable with me. Roll it out if and when you are confident.
