### ISSUE TITLE
Reach Map Not Updating

### ISSUE THREAD

**Issue by drewalth** [AmericanWhitewater/wh2o-vue#51]
**Describe the bug**
When I view one reach, then navigate to another, the map on the main-tab does not rebuild for the new reach. So If I go to Gore Canyon section of the Colorado then to The Numbers of the Arkansas, the map on the main tab shows Gore Canyon.

**Expected behavior**
maps to reflect the active reach.

**Screenshots**
![image](https://user-images.githubusercontent.com/16584198/81715808-e1299e00-9435-11ea-8a86-e1df5f2de921.png)
![image](https://user-images.githubusercontent.com/16584198/81715825-e71f7f00-9435-11ea-9876-ef336967001a.png)

**Potential Solution** 
May just need to add a watcher on reach detail ID to trigger rebuild.

**Comment by ngottlieb** [comment]
Yeah, I think this must be state related. I can work on it
