### ISSUE TITLE
Firefox Image Gallery Issue

### ISSUE THREAD

**Issue by ngottlieb** [AmericanWhitewater/wh2o-vue#527]
Charlie Walbridge reports that on Firefox at the bottom of the gallery page for a river page there are no options to see more then the 10 images on page 1, and no indication that more images exist.

**Comment by ngottlieb** [comment]
Hey @AWKevin I have thus far been unable to replicate this. Was there a specific reach page where it was a problem? I've viewed a few in Firefox and both been able to change the "Items per page" and navigate amongst pages.

**Comment by ngottlieb** [comment]
Actually, I do see this problem -- the bottom pagination controls disappearing -- across all browsers with very small screens / mobile! Maybe that's what he's referring to? I'll address that.

**Comment by ngottlieb** [comment]
k -- I did discover that the pagination controls were missing on mobile devices, so I have a fix for that here and will move it forward

**Comment by AWKevin** [comment]
I don't have a way to test this, but I suggest you move ahead with it.
