### ISSUE TITLE
Edit Feature Map Persists Between Reach Pages

### ISSUE THREAD

**Issue by ngottlieb** [AmericanWhitewater/wh2o-vue#536]
At the bottom of https://github.com/AmericanWhitewater/wh2o/issues/2734, @scottdharding wrote: 

```A similar issue occurs when you go to edit a river feature on a page if you have arrived via clicking on the map for another run: the map for that other run follows into the new river page and appears in the edit feature box.```

**Comment by ngottlieb** [comment]
Hey @scottdharding I'm actually having a hard time replicating this one. Can you explain exactly the route you go through to cause it, including clicking (and un-clicking) "Edit Mode?"

**Comment by scottdharding** [comment]
Here's the sequence:

1. Go to a river page (call this the originating page)
2. Click edit pencil (make edits on this page...or not, doesn't matter)
3. Click Map using left menu
4. Select a different river on the map and click the text link on the right to navigate to that page (call this the secondary page; you will still be in edit mode upon arrival)
5. Click Add Feature
6. The map that appears in the Add Feature box on the secondary page will be for the originating page.

See attached screen recording. You'll also notice that the map that opens in the Add Feature box on the secondary page does not fill the entire map area. This seems to be triggered by this sequence and doesn't occur unless navigating to a secondary page then clicking Add Feature.

https://user-images.githubusercontent.com/100976420/232856873-b32e6574-9193-4f21-89c9-88743812eb0d.mov

**Comment by ngottlieb** [comment]
OK, so I can replicate it when I click "Add Feature" (as you did in the video) but not when I do "Edit Feature." Your original comment referenced edit feature -- does edit feature work for you now and the issue is only on add feature?

**Comment by ngottlieb** [comment]
I've got changes that should make this work consistently across the board pending review, I'll let you know when it's on beta to test @scottdharding.

**Comment by ngottlieb** [comment]
@ryangroth5 needs review when you have a chance https://github.com/AmericanWhitewater/wh2o-vue/pull/541

**Comment by scottdharding** [comment]
> I've got changes that should make this work consistently across the board pending review, I'll let you know when it's on beta to test @scottdharding.

@ngottlieb Perhaps I mischaracterized it in my first statement and the issue only applied to adding a feature and not to editing a feature. I just tried a couple times to replicate the problem when editing a feature and couldn't make the problem occur like it did for adding a feature.

**Comment by ngottlieb** [comment]
It's up on beta now. @scottdharding your login on beta *should* be identical to prod (depending on when you last changed your password, etc.). In general, we do our best to test everything thoroughly before deploying it, so if you can't access beta we should resolve that. Try your normal login and let me know what happens.

**Comment by ngottlieb** [comment]
https://beta.americanwhitewater.org/

**Comment by scottdharding** [comment]
@ngottlieb My login does not work on beta. Would be great to fix that.

<img width="742" alt="Screenshot 2023-05-01 at 3 03 49 PM" src="https://user-images.githubusercontent.com/100976420/235539624-cf525581-3544-4c32-816d-7faaacb472d8.png">

**Comment by ngottlieb** [comment]
@scottdharding try it now, I copied your encrypted password from prod to the user entry on beta so it should use the same password. You may encounter some salesforce issues though as the beta account does not appear to be connected while the prod one is (our beta db must be old enough it didn't capture the account fix / update that happened for you last year).

**Comment by scottdharding** [comment]
@ngottlieb Thanks, I can log into beta now. I can't edit my trip reports (and they display w/p photos). Perhaps that's the salesforce issue rearing its head. Anyway, I'll test out the current issue w/edit feature map persistence.

**Comment by ngottlieb** [comment]
My guess is we refreshed the beta database partially, but not completely, leaving out users -- so the trip reports are with your newer account that's properly synced with Salesforce, while the one you have on beta is the older one (that's now been deleted/merged on the production website). You should be able to create new trip reports and edit those as needed

**Comment by ngottlieb** [comment]
@scottdharding did you get a chance to check out this edit feature issue on beta?

**Comment by scottdharding** [comment]
I did and it seems to have fixed the map persistence issue but I also encountered some edit quirks (maybe related to the fix, maybe not) that I haven’t had the time to fully document or understand. I’ll try to work on that tomorrow. Scott HardingStewardship AssociateAmerican WhitewaterForks of Salmon, CA541-840-1662On May 11, 2023, at 3:42 PM, Nick Gottlieb ***@***.***> wrote:﻿
@scottdharding did you get a chance to check out this edit feature issue on beta?

**Comment by AWKevin** [comment]
Is this on Production now? It is in the ready column.

**Comment by ngottlieb** [comment]
Yes, it's on production

**Comment by AWKevin** [comment]
I confirmed that this is fixed. Thanks!
