### ISSUE TITLE
Make Gauge Reading and "Current" Consistent in Flow Tab

### ISSUE THREAD

**Issue by ngottlieb** [AmericanWhitewater/wh2o-vue#549]
Subtask of https://github.com/AmericanWhitewater/wh2o/issues/2724.  As noted, the flow tab typically displays two different flows as "current." They should be consistent and accurate.

![Image](https://github.com/AmericanWhitewater/wh2o-vue/assets/1222063/43f3b02e-aff2-437e-8b8c-0ec7d35d58e0)

**Comment by ngottlieb** [comment]
@riversandcreeks the timestamped flow, "current," "high," and "low" should now be internally consistent on the flow tab. Up on beta for testing

**Comment by AWKevin** [comment]
Has this been added to production (it is in the ready column)

**Comment by ngottlieb** [comment]
yep

**Comment by AWKevin** [comment]
Looks good on Prod, thanks!
