### ISSUE TITLE
Rapid Edit Doesn't Always Pull In Rapid Data

### ISSUE THREAD

**Issue by ngottlieb** [AmericanWhitewater/wh2o-vue#71]
Try editing any rapid on Big Laurel (https://wh2o-vue.herokuapp.com/#/river-detail/1039).

I think the problem is that it's not set up to gracefully handle if there is no position set, so the component is crashing.

**Comment by ngottlieb** [comment]
cc: @AWKevin. In fixing this, I actually added a neat additional piece: if a rapid doesn't have a location specified, when you open the edit window, it uses `distance` to calculate where the point should be (which will then be saved).

**Comment by ngottlieb** [comment]
@AWKevin Drew just merged my PR so that issue with Big Laurel should be fixed now

**Comment by AWKevin** [comment]
Slick! That works great.
